# Generated by Django 5.0.6 on 2024-06-24 03:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0005_alter_actividad_clasificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Nivel_jerarquico', models.CharField(choices=[('Decano', 'Decano'), ('Vice Decano', 'Vice Decano'), ('Rector', 'Rector'), ('Jefe de departamento', 'Jefe de departamento'), ('Profesor', 'Profesor')], max_length=100)),
                ('Fecha_inicio', models.DateField(default=datetime.date.today)),
                ('Fecha_fin', models.DateField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('actividad_principal', models.ForeignKey(limit_choices_to={'tipo': 'Principal'}, on_delete=django.db.models.deletion.CASCADE, related_name='planes_principales', to='actividad.actividad')),
                ('actividades_generales', models.ForeignKey(limit_choices_to={'tipo': 'General'}, on_delete=django.db.models.deletion.CASCADE, related_name='planes_generales', to='actividad.actividad')),
            ],
        ),
    ]
