# Generated by Django 5.0.6 on 2024-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0007_alter_actividad_nombre'),
        ('plan_trabajo', '0002_alter_plan_trabajo_actividad_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_trabajo',
            name='actividad_principal',
        ),
        migrations.RemoveField(
            model_name='plan_trabajo',
            name='actividades_generales',
        ),
        migrations.AddField(
            model_name='plan_trabajo',
            name='actividad_principal',
            field=models.ManyToManyField(limit_choices_to={'Clasificacion': 'Principal'}, related_name='actividad_principal', to='actividad.actividad'),
        ),
        migrations.AddField(
            model_name='plan_trabajo',
            name='actividades_generales',
            field=models.ManyToManyField(limit_choices_to={'Clasificacion': 'General'}, related_name='actividades_generales', to='actividad.actividad'),
        ),
    ]
