# Generated by Django 5.0.6 on 2024-07-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0007_alter_actividad_nombre'),
        ('plan_trabajo', '0003_remove_plan_trabajo_actividad_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_trabajo',
            name='actividad_principal',
        ),
        migrations.AddField(
            model_name='plan_trabajo',
            name='actividades_principales',
            field=models.ManyToManyField(limit_choices_to={'Clasificacion': 'Principal'}, related_name='actividades_principales', to='actividad.actividad'),
        ),
        migrations.AlterField(
            model_name='plan_trabajo',
            name='Nivel_jerarquico',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Vice Decano', 'Vice Decano'), ('Rector', 'Rector'), ('Jefe de departamento', 'Jefe de departamento'), ('Profesor', 'Profesor')], max_length=100, verbose_name='Nivel jerárquico'),
        ),
        migrations.AlterField(
            model_name='plan_trabajo',
            name='Titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
