# Generated by Django 5.0.6 on 2024-06-18 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_rename_plan_trabajo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='Fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
