# Generated by Django 5.0.6 on 2024-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0005_alter_actividad_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='Clasificacion',
            field=models.CharField(choices=[('General', 'General'), ('Principal', 'Principal')], max_length=100, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='Nombre',
            field=models.CharField(max_length=10),
        ),
    ]
