# Generated by Django 5.0.6 on 2024-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0006_alter_actividad_clasificacion_alter_actividad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='Nombre',
            field=models.CharField(max_length=20),
        ),
    ]
