# Generated by Django 5.0.6 on 2024-07-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_trabajo_individual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_trabajo_individual',
            name='clasification',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('No_aprobado', 'No aprobado')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
