# Generated by Django 5.0.6 on 2024-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0007_alter_actividad_nombre'),
        ('plan_trabajo_individual', '0002_plan_trabajo_individual_clasification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_trabajo_individual',
            name='actividad_principal',
        ),
        migrations.RemoveField(
            model_name='plan_trabajo_individual',
            name='actividades_generales',
        ),
        migrations.AlterField(
            model_name='plan_trabajo_individual',
            name='clasification',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], max_length=30),
        ),
        migrations.AddField(
            model_name='plan_trabajo_individual',
            name='actividad_principal',
            field=models.ManyToManyField(limit_choices_to={'Clasificacion': 'Principal'}, related_name='actividad_principal_pti', to='actividad.actividad'),
        ),
        migrations.AddField(
            model_name='plan_trabajo_individual',
            name='actividades_generales',
            field=models.ManyToManyField(limit_choices_to={'Clasificacion': 'General'}, related_name='actividades_generales_pti', to='actividad.actividad'),
        ),
    ]
