# Generated by Django 5.0.6 on 2024-07-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_trabajo_individual', '0003_remove_plan_trabajo_individual_actividad_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_trabajo_individual',
            name='Nivel_jerarquico',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Vice Decano', 'Vice Decano'), ('Rector', 'Rector'), ('Jefe de departamento', 'Jefe de departamento'), ('Profesor', 'Profesor')], max_length=100, verbose_name='Nivel Gerárquico'),
        ),
        migrations.AlterField(
            model_name='plan_trabajo_individual',
            name='Titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='plan_trabajo_individual',
            name='clasification',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], max_length=30, verbose_name='Clasificación'),
        ),
    ]
