# Generated by Django 5.0.6 on 2024-06-25 05:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantilla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='area1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_del_area', models.CharField(max_length=200)),
                ('Cantidad_de_personal', models.IntegerField()),
                ('Fecha', models.DateField(default=datetime.date.today)),
                ('Encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantilla.plantilla')),
            ],
        ),
    ]
