# Generated by Django 5.0.6 on 2024-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_defaultuser_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='Rol_de_usuario',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Vice Decano', 'Vice Decano'), ('Rector', 'Rector'), ('Jefe de departamento', 'Jefe de departamento'), ('Profesor', 'Profesor')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
