# Generated by Django 5.0.6 on 2024-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_defaultuser_rol_de_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='Rol_de_usuario',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Vice Decano', 'Vice Decano'), ('Rector', 'Rector'), ('Jefe de departamento', 'Jefe de departamento'), ('Profesor', 'Profesor')], max_length=30, null=True),
        ),
    ]
