# Generated by Django 5.0.6 on 2024-07-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_defaultuser_rol_de_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1),
        ),
    ]
