# Generated by Django 5.0.6 on 2024-07-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_defaultuser_is_jefe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultuser',
            old_name='area',
            new_name='Área',
        ),
    ]
