# Generated by Django 5.0.6 on 2024-06-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_cumplimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_cumplimiento',
            name='Cumplidas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informe_cumplimiento',
            name='Incumplidas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informe_cumplimiento',
            name='Modificadas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informe_cumplimiento',
            name='Nuevas_incorporadas',
            field=models.IntegerField(),
        ),
    ]
