# Generated by Django 5.0.6 on 2024-06-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_cumplimiento', '0002_alter_informe_cumplimiento_cumplidas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_cumplimiento',
            name='Total_tareas_planificadas',
            field=models.IntegerField(),
        ),
    ]
