# Generated by Django 5.0.6 on 2024-06-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_cumplimiento', '0003_alter_informe_cumplimiento_total_tareas_planificadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_cumplimiento',
            name='Descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
