# Generated by Django 5.0.6 on 2024-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_cumplimiento', '0004_alter_informe_cumplimiento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe_cumplimiento',
            name='Titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
